---
apiVersion: nmstate.io/v1alpha1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: bond1
spec:
  desiredState:
    interfaces:
    - name: bond1
      type: bond
      ipv4:
        auto-dns: false
        auto-gateway: false
        auto-routes: false
        dhcp: true
        enabled: true
      state: up
      link-aggregation:
        mode: balance-rr
        options:
          miimon: '140'
        slaves:
        - ens8
        - ens9
